FROM docker.io/python:3.13.3-bookworm AS backend

# Set the working directory
COPY ./backend /app
WORKDIR /app

# Set shell to bash
RUN ln -sf /bin/bash /bin/sh

# Install dependencies
RUN python -m venv venv
RUN source venv/bin/activate
RUN pip3 install -r requirements.txt 

# Environment variables
ENV BACKEND_PORT=3001
ENV HOST=::
ENV ENVIRONMENT="development"
ENV API_KEY=""
ENV VYOS_HOST=""
ENV VYOS_API_URL=""
ENV CERT_PATH=""
ENV TRUST_SELF_SIGNED="false"
ENV HTTPS="true"

# Setup port
EXPOSE ${BACKEND_PORT}

# Set the entrypoint
RUN chmod +x start.sh
ENTRYPOINT [ "./start.sh" ]
