FROM docker.io/node:18-alpine AS frontend-builder

# Copy frontend source code
COPY ./frontend/ /app

# Set working directory for frontend
WORKDIR /app

# Install frontend dependencies
RUN npm ci

ENV NEXT_PUBLIC_API_URL=http://localhost:3001
ENV NODE_ENV=production
ENV FRONTEND_PORT=3000

EXPOSE ${FRONTEND_PORT}

RUN chmod +x start.sh

ENTRYPOINT [ "./start.sh" ]